server:
  port: 8080

spring:
  application:
    name: incident-management

  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5433}/incident_db
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # schema do Flyway quản lý, JPA chỉ validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-in-production-min-256-bits-long}
    expiration-ms: 86400000   # 24h
  encryption:
    key: ${APP_ENCRYPTION_KEY:MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=}   # AES-256 key (base64) - ĐỔI khi triển khai thật

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.attt.incident: DEBUG
    org.springframework.security: INFO
