ALTER TABLE incident_iocs ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE incident_iocs ADD COLUMN IF NOT EXISTS removed_at TIMESTAMP;
ALTER TABLE incident_iocs ADD COLUMN IF NOT EXISTS removed_by BIGINT REFERENCES users(id);
